create table JOB_HISTORY
(
    EMPLOYEE_ID   NUMBER(6)    not null
        constraint JHIST_EMP_FK
            references EMPLOYEES
        constraint JHIST_EMPLOYEE_NN
            check ("EMPLOYEE_ID" IS NOT NULL),
    START_DATE    DATE         not null
        constraint JHIST_START_DATE_NN
            check ("START_DATE" IS NOT NULL),
    END_DATE      DATE         not null
        constraint JHIST_END_DATE_NN
            check ("END_DATE" IS NOT NULL),
    JOB_ID        VARCHAR2(10) not null
        constraint JHIST_JOB_FK
            references JOBS
        constraint JHIST_JOB_NN
            check ("JOB_ID" IS NOT NULL),
    DEPARTMENT_ID NUMBER(4)
        constraint JHIST_DEPT_FK
            references DEPARTMENTS,
    constraint JHIST_EMP_ID_ST_DATE_PK
        primary key (EMPLOYEE_ID, START_DATE),
    constraint JHIST_DATE_INTERVAL
        check (end_date > start_date)
)
/

INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (102, DATE '1993-01-13', DATE '1998-07-24', 'IT_PROG', 60);
INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (101, DATE '1989-09-21', DATE '1993-10-27', 'AC_ACCOUNT', 110);
INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (101, DATE '1993-10-28', DATE '1997-03-15', 'AC_MGR', 110);
INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (201, DATE '1996-02-17', DATE '1999-12-19', 'MK_REP', 20);
INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (114, DATE '1998-03-24', DATE '1999-12-31', 'ST_CLERK', 50);
INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (122, DATE '1999-01-01', DATE '1999-12-31', 'ST_CLERK', 50);
INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (200, DATE '1987-09-17', DATE '1993-06-17', 'AD_ASST', 90);
INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (176, DATE '1998-03-24', DATE '1998-12-31', 'SA_REP', 80);
INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (176, DATE '1999-01-01', DATE '1999-12-31', 'SA_MAN', 80);
INSERT INTO U23.JOB_HISTORY (EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES (200, DATE '1994-07-01', DATE '1998-12-31', 'AC_ACCOUNT', 90);
